# Generated by Django 2.0.5 on 2018-08-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_social', '0002_profile_favorite_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_articles',
        ),
    ]
