# Generated by Django 2.0.5 on 2018-08-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_social', '0004_profile_favorite_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to='social_content.Content'),
        ),
    ]
