# Generated by Django 2.1.3 on 2018-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_content', '0012_remove_content_favorite_articles'),
        ('account_social', '0009_remove_profile_favorite_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to='social_content.Content'),
        ),
    ]
