# Generated by Django 2.1.3 on 2018-11-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_social', '0010_profile_favorite_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to='social_content.Content'),
        ),
    ]
