# Generated by Django 2.1.3 on 2018-11-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_social', '0010_auto_20181110_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_articles',
        ),
    ]
