# Generated by Django 2.1.3 on 2019-02-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_social', '0018_auto_20190223_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to='social_content.Content'),
        ),
    ]
