# Generated by Django 2.0.5 on 2018-06-14 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='content_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
