# Generated by Django 2.0.5 on 2018-06-20 14:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_content', '0002_content_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='entry',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Запись'),
        ),
    ]
