# Generated by Django 2.0.5 on 2018-08-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_content', '0003_auto_20180620_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='user_likes',
            new_name='users_like',
        ),
    ]
