# Generated by Django 2.0.5 on 2018-08-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_content', '0005_auto_20180805_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='user_like',
            new_name='user_likes',
        ),
    ]
