# Generated by Django 2.0.5 on 2018-08-05 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_content', '0006_auto_20180805_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
