# Generated by Django 2.0.5 on 2018-08-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_content', '0007_content_favorite_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='favorite_articles',
        ),
    ]
