# Generated by Django 2.0.5 on 2018-08-06 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_content', '0008_remove_content_favorite_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
