# Generated by Django 2.0.5 on 2018-08-06 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_content', '0010_auto_20180806_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritearticle',
            name='Article',
        ),
        migrations.RemoveField(
            model_name='favouritearticle',
            name='user',
        ),
        migrations.AddField(
            model_name='content',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavouriteArticle',
        ),
    ]
