# Generated by Django 2.0.5 on 2018-08-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_content', '0011_auto_20180806_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='favorite_articles',
        ),
    ]
